### ISSUE TITLE
Atomize Query Results into Panels

### ISSUE THREAD

**Issue by srwaggon** [inpho/inphosemantics-frontend#20]
Currently, after the combinations for requests have been submitted and results have returned, all of the data is rendered as a giant tree-like table, containing a first order of copora, a second order of models, a third order of phrases and lastly the results.

I personally feel that this is a little ungainly and could be optimized if the cascading tables were converted into atomic panels for each combination. For example, instead of the table titled "Stanford Encyclopedia of Philosophy: Complete" having two child tables, "Beagle: Order Vectors" & "Beagle: Context Vectors", each of which having a child table for each phrase, I'd like to imagine that there would be a panel for each combination. That is, there would be a panel "SEP:Complete & Beagle: Order & Kant" as well as "SEP: Complete & Beagle: Order & Descartes" as well as "SEP: Complete & Beagle: Context & Kant", etc.

I believe that the paneling would be a good (although nontrivial) idea insofar as creating visual separation between query results as well as the future possibility of relocating particular panels so that the user may be able to place specific query-results side-by-side. This is somewhat related to the enhancement idea #17.

**Comment by colinallen** [comment]
I like the idea of being able to move around the subtables at will -- although we should have a meeting specifically to discuss the future of this interface -- currently it's very useful for demos (I used it multiple times yesterday here at Woods Hole MBL) but for actual analysis and visualization work, it may just be a portal to the data rather than a primary visualization tool.  But that said, I think we can add some very useful enhancements to it.

**Comment by srwaggon** [comment]
Panel'd.

**Comment by colinallen** [comment]
Great, thanks.  Reopening this because one slight change request:  Can you make the box equal to the size of the list, instead of scrolling?  Reason for this is that it makes it inconvenient to see the cross panel highlighting when more than the pre-fixed number of terms (20) is selected.  Also, if you choose less than 20, the fixed panel size leaves whitespace at the end.

**Comment by srwaggon** [comment]
In reviewing revisions, please also check http://inphodata.cogs.indiana.edu:9090 for how it would appear with the corpus / model labels in each query box formatted properly. I'm open to thoughts and suggestions.

**Comment by colinallen** [comment]
Box size looks fine (although terms returned at port 9090 appear to be dummies).
