### ISSUE TITLE
menu bar width for a lot of results

### ISSUE THREAD

**Issue by rrose1** [inpho/inphosemantics-frontend#9]
At the moment you can select as much stuff as you want. I'm not opposed to leaving it like that for now (especially because limiting the columns will require additional interface engineering). Still if we do, the menu bar should stretch out all the way. Right now, if you submit a ton of selections, the menu bar ends at 1000px or so even though the table keeps going. This looks bad.

**Comment by srwaggon** [comment]
With the code restructured, I don't see this happening anymore.

The problem was that the contents of the page overflowed outside of the page width, creating a scroll bar for the content, but not for the page "container" (the thing overflowing). Since the title bar kept with the width of the container, despite the contents taking up more width, the title bar refused to stretch.

Now, the container always fills the entire page, and the elements float, preventing overflowing. Thus the titlebar is always full-width.
